title: Sentra Documentation
description: Official documentation for the Sentra Programming Language - A security-focused programming language with built-in networking capabilities
theme: just-the-docs

url: https://sentra-language.github.io
baseurl: /sentra

aux_links:
  "GitHub Repository": "https://github.com/sentra-language/sentra"
  "Download Latest": "https://github.com/sentra-language/sentra/releases"

# Footer content
footer_content: "Copyright &copy; 2025 Sentra Language. Distributed under the <a href=\"https://github.com/sentra-language/sentra/blob/main/LICENSE\">MIT License</a>."