# Sentra Language Documentation
title: "Sentra Documentation"
description: "Official documentation for the Sentra Programming Language"
baseurl: "/sentra"
url: "https://sentra-language.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs@v0.7.0

# Jekyll configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Permalinks
permalink: pretty

# Just the Docs settings
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Aux links
aux_links:
  "GitHub":
    - "https://github.com/sentra-language/sentra"
  "Download":
    - "https://github.com/sentra-language/sentra/releases"

aux_links_new_tab: true

# Collections
collections:
  tutorial:
    output: true
    permalink: /tutorial/:name/
  library:
    output: true
    permalink: /library/:name/
  reference:
    output: true
    permalink: /reference/:name/
  guide:
    output: true
    permalink: /guide/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "tutorial"
    values:
      layout: "tutorial"
      sidebar: tutorial
  - scope:
      path: ""
      type: "library"
    values:
      layout: "library"
      sidebar: library
  - scope:
      path: ""
      type: "reference"
    values:
      layout: "reference"
      sidebar: reference
  - scope:
      path: ""
      type: "guide"
    values:
      layout: "guide"
      sidebar: guide

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md

# Plugins (if needed for GitHub Pages)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag