# Site settings
title: "Sentra Documentation"
description: "Official documentation for the Sentra Programming Language - A security-focused programming language with built-in networking capabilities"
baseurl: "/sentra"
url: "https://sentra-language.github.io"

# Build settings  
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
  sass_dir: _sass
  sourcemap: never

# Just the Docs theme
remote_theme: just-the-docs/just-the-docs@v0.8.2

# Theme configuration
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Code highlighting
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    default_lang: javascript

# Navigation
nav_sort: case_insensitive

# Aux links
aux_links:
  "GitHub Repository":
    - "//github.com/sentra-language/sentra"
  "Download Latest": 
    - "//github.com/sentra-language/sentra/releases"

aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2025 Sentra Language. Distributed under the <a href=\"https://github.com/sentra-language/sentra/blob/main/LICENSE\">MIT License</a>."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# GitHub edit links
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/sentra-language/sentra"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Heading anchors
heading_anchors: true

# Exclude
exclude:
  - ".sass-cache/"
  - ".jekyll-cache/"
  - "gemfiles/"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules/"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag