# Sentra Language Documentation
title: "Sentra Documentation"
description: "Official documentation for the Sentra Programming Language - A security-focused programming language"
baseurl: "/sentra"
url: "https://sentra-language.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs@v0.7.0

# Jekyll configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink: pretty

# Just the Docs settings
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Navigation
nav_fold: false
nav_sort: case_insensitive

# Aux links
aux_links:
  "GitHub Repository":
    - "https://github.com/sentra-language/sentra"
  "Download Latest":
    - "https://github.com/sentra-language/sentra/releases"

aux_links_new_tab: true

# Footer
footer_content: "Copyright &copy; 2025 Sentra Language. Distributed under the <a href=\"https://github.com/sentra-language/sentra/blob/main/LICENSE\">MIT License</a>."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/sentra-language/sentra"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag