# Sentra Language Documentation
title: "Sentra Documentation"
description: "Official documentation for the Sentra Programming Language - A security-focused programming language with built-in networking capabilities"
baseurl: ""
url: "https://sentra-language.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs@v0.7.0

# Jekyll configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1

# Permalinks
permalink: pretty

# Just the Docs theme settings
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/sentra-language/sentra
    hide_icon: false
  - title: Download Latest
    url: https://github.com/sentra-language/sentra/releases
    hide_icon: false

# Footer
footer_content: "Copyright &copy; 2025 Sentra Language. Distributed under the <a href=\"https://github.com/sentra-language/sentra/blob/main/LICENSE\">MIT License</a>."

# GitHub edit links
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/sentra-language/sentra"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Heading anchor links
heading_anchors: true

# Aux links for header
aux_links:
  "GitHub":
    - "https://github.com/sentra-language/sentra"
  "Download":
    - "https://github.com/sentra-language/sentra/releases"

aux_links_new_tab: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE
  - "*.gemspec"
  - "*.gem"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache